'''
You are given two strings s and t.

String t is generated by random shuffling string
s and then add one more letter at a random position.

Return the letter that was added to t.
'''


def find_the_difference(s: str, t: str) -> str:
    s_dict = {}
    t_dict = {}
    for letter in s:
        if letter not in s_dict:
            s_dict[letter] = 1
        else:
            s_dict[letter] += 1
    for letter in t:
        if letter not in t_dict:
            t_dict[letter] = 1
        else:
            t_dict[letter] += 1
    for letter in t:
        if letter not in s_dict or s_dict[letter] != t_dict[letter]:
            return letter
    return t[0]


print(find_the_difference("aa", "aa"))
