name: Pandas tests

on:
  push:
    branches:
      - main
    paths:
      - 'Pandas/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Pandas

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytest

      - name: Run tests
        run: pytest pandas_tests.py
